### ISSUE TITLE
Missing region endpoints

### ISSUE THREAD

**Issue by PatMyron** [awsdocs/amazon-rds-user-guide#43] opened 2018-11-14 20:34 UTC
I can't find the table in the source file but this page contains a table of endpoints:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html 
that is missing the GovCloud US-East, Osaka, and Ningxia endpoints
https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/

**Comment by randyurbano** [comment] 2018-11-15 00:38
Thanks for your feedback. I confirmed that you are correct. I will update the documentation.

**Comment by randyurbano** [comment] 2018-11-16 19:31
The updated documentation is public:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html

Thanks again for your help. If you agree that the issue is resolved, please close the issue.

**Comment by PatMyron** [comment] 2018-11-16 19:34
Should "AWS GovCloud (US)" be "AWS GovCloud (US-West)" to clarify?

**Comment by randyurbano** [comment] 2018-11-16 19:40
Yes, it should. I fixed the issue by using automatic generation of the table. Previously, it was not automatically generated. The team responsible automatically generating region tables knows about this error, and it will be fixed soon. You can see the same issue in the AWS General Reference:

https://docs.aws.amazon.com/general/latest/gr/rande.html?id=docs_gateway#rds_region

That reference is using the same method for automatic generation of the table.

**Closed** 2018-11-19 19:00 UTC
